apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "echome.fullname" . }}
  labels:
    {{- include "echome.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "echome.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "echome.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- toYaml .Values.deployment.ports | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.deployment.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.deployment.readinessProbe | nindent 12 }}
          env:
            {{- toYaml .Values.deployment.env | nindent 12 }}
      