apiVersion: v1
kind: Service
metadata:
  name: {{ include "echome.fullname" . }}
  labels:
    {{- include "echome.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
{{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
{{- end }}
  selector:
    {{- include "echome.selectorLabels" . | nindent 4 }}
