apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echome-app
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: 4-argocd/echome
    repoURL: 'https://github.com/gablemire/echome.git'
    targetRevision: HEAD
    directory:
      jsonnet:
        tlas:
          - {}
      recurse: true
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
