apiVersion: v1
kind: Service
metadata:
  name: argocd-server-nodeport
  namespace: argocd
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30180
      protocol: TCP
  selector:
    app.kubernetes.io/name: argocd-server
