apiVersion: v1
kind: Service
metadata:
  name: echome
spec:
  type: NodePort
  selector:
    app: echome
  ports:
    - port: 8583
      targetPort: 8583
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
